version: '3.7'

services:
  web:
    build: ./auto
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./auto/.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=auto
