# Generated by Django 3.0.2 on 2020-01-19 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.CreateModel(
            name='Reservations_cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата аренды')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата возвращения')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Cars')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Аренда машины',
                'verbose_name_plural': 'Аренда машин',
            },
        ),
    ]
